"""create initial tables

Revision ID: 9bef20601ad9
Revises: 
Create Date: 2026-04-18 11:38:42.397222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bef20601ad9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('external_id', sa.String(length=128), nullable=True, comment='External ID from the Applicant Tracking System'),
    sa.Column('full_name', sa.String(length=256), nullable=False, comment="Candidate's full name"),
    sa.Column('email', sa.String(length=320), nullable=True, comment="Candidate's email address"),
    sa.Column('phone', sa.String(length=32), nullable=True, comment='Phone number with country code'),
    sa.Column('location_city', sa.String(length=128), nullable=True),
    sa.Column('location_country', sa.String(length=64), nullable=True, comment='ISO country name for search filtering'),
    sa.Column('years_of_experience', sa.SmallInteger(), nullable=True),
    sa.Column('current_title', sa.String(length=256), nullable=True),
    sa.Column('current_company', sa.String(length=256), nullable=True),
    sa.Column('education_level', sa.String(length=64), nullable=True, comment='Bachelors, Masters, PhD, etc.'),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON array of skills, e.g. ["Python", "AWS", "FastAPI"]'),
    sa.Column('resume_text', sa.Text(), nullable=True, comment='Plain text resume content (max ~8000 chars), used for LLM reasoning'),
    sa.Column('resume_blob_url', sa.String(length=1024), nullable=True, comment='Azure Blob Storage URL to the original resume file'),
    sa.Column('vector_id', sa.String(length=256), nullable=True, comment="ID of this candidate's vector in Azure AI Search index"),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Soft-delete flag. False = candidate opted out or was removed.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index('ix_candidates_country_experience', 'candidates', ['location_country', 'years_of_experience'], unique=False)
    op.create_index(op.f('ix_candidates_is_active'), 'candidates', ['is_active'], unique=False)
    op.create_index(op.f('ix_candidates_location_country'), 'candidates', ['location_country'], unique=False)
    op.create_index(op.f('ix_candidates_vector_id'), 'candidates', ['vector_id'], unique=False)
    op.create_index(op.f('ix_candidates_years_of_experience'), 'candidates', ['years_of_experience'], unique=False)
    op.create_table('prompt_variants',
    sa.Column('name', sa.String(length=128), nullable=False, comment="Human Readable name like 'v2 concise scoring"),
    sa.Column('description', sa.Text(), nullable=True, comment='What this variant changes and why we are testing it'),
    sa.Column('system_prompt', sa.Text(), nullable=False, comment='The system prompt template for GPT-40-mini'),
    sa.Column('user_prompt_template', sa.Text(), nullable=False, comment='The user template with {jd_text},{skills},etc.placeholders'),
    sa.Column('temperature', sa.Float(), nullable=False, comment='LLM temperature (0 deterministic 1 ceative )'),
    sa.Column('traffic_percentage', sa.SmallInteger(), nullable=False, comment='Percentage of traffic routed to this variant (0-100). All variants must sum to 100.'),
    sa.Column('is_production', sa.Boolean(), nullable=False, comment='Whether this is the current production prompt'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether this variant is active in experiments'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('search_events',
    sa.Column('recruiter_id', sa.String(length=256), nullable=False, comment='Recruiter identifier from JWT claims'),
    sa.Column('jd_text_hash', sa.String(length=64), nullable=False, comment='SHA-256 hex hash of the 3d test'),
    sa.Column('jd_raw_text', sa.Text(), nullable=False, comment='Full archived JD text for audit replay'),
    sa.Column('jd_file_name', sa.String(length=512), nullable=True, comment='Original filename if uploaded as PDF/DOCX (null if pasted as text)'),
    sa.Column('top_candidates_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Ordered list of top 20 candidate UUIDs returned by the pipeline'),
    sa.Column('latency_embedding_ms', sa.Integer(), nullable=True, comment='time to generate /retrieve 3D embedding (ms)'),
    sa.Column('latency_stage1_ms', sa.Integer(), nullable=True, comment='stage 1 ANN vecor search latency (ms)'),
    sa.Column('latency_stage2_ms', sa.Integer(), nullable=True, comment='Stage  2 LLm reasoning latency'),
    sa.Column('total_latency_ms', sa.Integer(), nullable=True, comment='Total end to end pipeline latency'),
    sa.Column('candidates_searched', sa.Integer(), nullable=True),
    sa.Column('embedding_cache_hit', sa.Boolean(), nullable=True, comment='Whether the embedding was served from Redis cache'),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_events_jd_text_hash'), 'search_events', ['jd_text_hash'], unique=False)
    op.create_index(op.f('ix_search_events_recruiter_id'), 'search_events', ['recruiter_id'], unique=False)
    op.create_table('match_results',
    sa.Column('search_event_id', sa.UUID(), nullable=False, comment='The search that produced this match'),
    sa.Column('candidate_id', sa.UUID(), nullable=False, comment='The candidate who was scored'),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=False, comment="GPT-4o-mini's match score (0.00 - 100.00)"),
    sa.Column('vector_similarity', sa.Numeric(precision=8, scale=6), nullable=False, comment='Raw cosine similarity from Azure AI Search HNSW'),
    sa.Column('justification_bullet_1', sa.Text(), nullable=False, comment="LLM's top reason for the match score"),
    sa.Column('justification_bullet_2', sa.Text(), nullable=False, comment="LLM's secondary reason or identified gap"),
    sa.Column('rank', sa.SmallInteger(), nullable=False, comment='Rank within the search result (1 = best match, 20 = last)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_event_id'], ['search_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_results_candidate_id'), 'match_results', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_match_results_search_event_id'), 'match_results', ['search_event_id'], unique=False)
    op.create_table('prompt_experiments',
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('search_event_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('score_given', sa.Float(), nullable=False, comment='Match score produced by this prompt variant'),
    sa.Column('latency_ms', sa.Integer(), nullable=False, comment='Time taken for LLM to respond (ms)'),
    sa.Column('tokens_used', sa.Integer(), nullable=False, comment='Total tokens (prompt + completion) consumed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_event_id'], ['search_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['prompt_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_experiments_search_event_id'), 'prompt_experiments', ['search_event_id'], unique=False)
    op.create_index(op.f('ix_prompt_experiments_variant_id'), 'prompt_experiments', ['variant_id'], unique=False)
    op.create_table('rai_reports',
    sa.Column('search_event_id', sa.UUID(), nullable=False, comment='The search that this report analyses'),
    sa.Column('demographic_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Aggregate stats: {"country": {"India": 12, "USA": 5}}'),
    sa.Column('score_variance_by_group', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Mean/stddev of match_score grouped by country, experience, education'),
    sa.Column('bias_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Potential bias warnings: ["95% of top results from single country"]'),
    sa.Column('jd_inclusivity_score', sa.SmallInteger(), nullable=True, comment='LLM-rated JD inclusivity (1-10)'),
    sa.Column('exclusionary_phrases', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Flagged phrases: [{"phrase": "rockstar", "suggestion": "top performer"}]'),
    sa.Column('filter_impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='How filters affected diversity'),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Actionable suggestions to improve JD inclusivity and search breadth'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['search_event_id'], ['search_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_event_id')
    )
    op.create_table('webhook_events',
    sa.Column('match_result_id', sa.UUID(), nullable=False, comment='The high-scoring match that triggered this webhook'),
    sa.Column('webhook_url', sa.String(length=2048), nullable=False, comment='The URL that received (or should have received) the webhook'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='The JSON payload that was sent'),
    sa.Column('http_status', sa.SmallInteger(), nullable=True, comment='HTTP status code from the webhook receiver (null if request failed)'),
    sa.Column('response_body', sa.Text(), nullable=True, comment='Response body from the webhook receiver (for debugging)'),
    sa.Column('attempt_number', sa.SmallInteger(), nullable=False, comment='Which delivery attempt this is (1, 2, or 3)'),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When this delivery attempt was initiated'),
    sa.Column('succeeded_at', sa.DateTime(timezone=True), nullable=True, comment='When delivery was confirmed (null if failed)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['match_result_id'], ['match_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_events_match_result_id'), 'webhook_events', ['match_result_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_match_result_id'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_table('rai_reports')
    op.drop_index(op.f('ix_prompt_experiments_variant_id'), table_name='prompt_experiments')
    op.drop_index(op.f('ix_prompt_experiments_search_event_id'), table_name='prompt_experiments')
    op.drop_table('prompt_experiments')
    op.drop_index(op.f('ix_match_results_search_event_id'), table_name='match_results')
    op.drop_index(op.f('ix_match_results_candidate_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_index(op.f('ix_search_events_recruiter_id'), table_name='search_events')
    op.drop_index(op.f('ix_search_events_jd_text_hash'), table_name='search_events')
    op.drop_table('search_events')
    op.drop_table('prompt_variants')
    op.drop_index(op.f('ix_candidates_years_of_experience'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_vector_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_location_country'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_is_active'), table_name='candidates')
    op.drop_index('ix_candidates_country_experience', table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
